[package]
name = "karafriends"
version = "0.1.0"
authors = ["Connor Worley <connorbworley@gmail.com>"]
edition = "2018"
exclude = ["index.node"]

[lib]
name = "karafriends"
crate-type = ["cdylib"]

[dependencies]
aubio-rs = "0.1.3"
futures = "0.3.14"
cpal = "0.13.3"
neon = { version = "0.8.0", default-features = false, features = ["napi-4"] }
ringbuf = "0.2.4"

[build-dependencies]
neon-build = "0.8.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
